### ISSUE TITLE
优化流程的时间复杂度

### ISSUE THREAD

**Issue by Floating-Ocean** [qwedc001/Peeper-Board-Generator#10]
考虑到刷新 problemStat(P) 和 rp(R) 在题库数量很多或用户数量很多的情况下，时间开销很大，因而考虑以下方法进行规避，用空间换时间：
1. --full: 当天获取过昨日总榜后，直接读取信息，不用刷新 P, R；
2. --now: 如果当天未获取过昨日总榜，则自动调用 --full 先更新一下数据（或者封装个函数）。否则，读取昨日总榜中的题数数据，并爬取当天的所有提交，进行一个累加，然后排序即可，因为我们需要的是题数排名而非 rp 排名，所以这样可以规避刷新 P, R

**Comment by qwedc001** [comment]
其实我在想，这个优化是针对hydro的还是针对整个项目的，单看跟hydro强相关，但好像实际上要达成的效果就是直接读取封装好的data.json并且送到榜单生成器里面。
先开个branch写写看
