### ISSUE TITLE
开放更多命令行参数

### ISSUE THREAD

**Issue by Floating-Ocean** [qwedc001/Peeper-Board-Generator#11]
1. 当前版本号;
2. 根据用户uid查询用户信息，根据用户名模糊匹配并查询用户信息（可爬取ranking来获取用户列表，然后使用difflib.get_close_matches）

**Comment by qwedc001** [comment]
将在稍后修复

**Comment by qwedc001** [comment]
> 2. 根据用户uid查询用户信息，根据用户名模糊匹配并查询用户信息（可爬取ranking来获取用户列表，然后使用difflib.get_close_matches）

明确一下用户uid信息匹配后返回什么。
