### ISSUE TITLE
模拟登录的网址存在问题

### ISSUE THREAD

**Issue by Floating-Ocean** [qwedc001/Peeper-Board-Generator#9]
如题，会出现 oj/d/domain//login 的情况

**Comment by qwedc001** [comment]
ddl：7.31



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月31日(周三) 晚上8:58
收件人: ***@***.***&gt;;
抄送: "Eric ***@***.******@***.***&gt;;
主题: [qwedc001/Peeper-Board-Generator] 模拟登录的网址存在问题 (Issue #9)




 
如题，会出现 oj/d/domain//login 的情况
